[en]
title = "Jiang Wenrui's Website"
languageCode = "en"
weight = 1
languageName = "English"
contentDir = "content/english"

[zh]
title = "蒋文睿的网站"
languageCode = "zh"
weight = 2
languageName = "中文"
contentDir = "content/Chinese"
