[[main]]
name = "首页"
identifier = "home"
weight = 100
url = "/zh/"

[[main]]
name = "经历"
weight = 200
identifier = "experience"
url = "/zh/post/"

[[main]]
name = "文章"
weight = 300
identifier = "articles"
url = "/zh/portfolio/"

[[main]]
name = "项目"
weight = 400
identifier = "project"
url = "/zh/project/"

[[main]]
name = "荣誉"
weight = 500
identifier = "awards"
url = "/zh/awards/"

[[main]]
name = "联系"
weight = 600
identifier = "contact"
url = "/zh/contact/"
