[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Experience"
weight = 200
identifier = "experience"
url = "/post/"

[[main]]
name = "Articles"
weight = 300
identifier = "articles"
url = "/portfolio/"

[[main]]
name = "Project"
weight = 400
identifier = "project"
url = "/project/"

[[main]]
name = "Awards"
weight = 500
identifier = "awards"
url = "/awards/"

[[main]]
name = "Contact"
weight = 600
identifier = "contact"
url = "/contact/"
