[[main]]
name = "Start"
identifier = "home"
weight = 100
url = "/de/"

[[main]]
name = "Erfahrung"
identifier = "experience"
weight = 200
url = "/de/post/"

[[main]]
name = "Artikel"
identifier = "articles"
weight = 300
url = "/de/portfolio/"

[[main]]
name = "Projekt"
identifier = "project"
weight = 400
url = "/de/project/"

[[main]]
name = "Auszeichnungen"
identifier = "awards"
weight = 500
url = "/de/awards/"

[[main]]
name = "Kontakt"
identifier = "contact"
weight = 600
url = "/de/contact/"
