[[main]]
name = "首页"
identifier = "home"
weight = 100
url = "/zh/"

[[main]]
name = "经历"
weight = 200
identifier = "experience"
url = "/zh/post/"

[[main]]
name = "文章"
weight = 300
identifier = "articles"
url = "/zh/portfolio/"

[[main]]
name = "关于"
weight = 400
identifier = "about"
url = "/zh/about/"

[[main]]
name = "成果"
weight = 500
identifier = "accomplishments"

[[main]]
name = "荣誉"
weight = 510
identifier = "awards"
url = "/zh/awards/"
parent = "accomplishments"

[[main]]
name = "证书"
weight = 520
identifier = "certifications"
url = "/zh/certifications/"
parent = "accomplishments"

[[main]]
name = "联系"
weight = 600
identifier = "contact"
url = "/zh/contact/"

[[footer]]
name = "法律声明"
weight = 1
identifier = "imprint"
url = "/zh/imprint/"
