  [[main]]
  name = "主页"
  identifier = "home"
  weight = 100
  url = "/zh/"

  [[main]]
  name = "文章"
  weight = 200
  identifier = "posts"
  url = "/zh/post/"

  [[main]]
  name = "项目"
  weight = 300
  identifier = "portfolio"
  url = "/zh/portfolio/"

  [[main]]
  name = "关于"
  weight = 400
  identifier = "about"
  url = "/zh/about/"

  [[main]]
  name = "成就"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "荣誉"
  weight = 510
  identifier = "awards"
  url = "/zh/awards/"
  parent = "accomplishments"  

  [[main]]
  name = "认证"
  weight = 520
  identifier = "certifications"
  url = "/zh/certifications/"
  parent = "accomplishments"

  [[main]]
  name = "联系"
  weight = 600
  identifier = "contact"
  url = "/zh/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/zh/imprint/"
