baseURL = "https://jiangwenrui.com/"
title = "Jiang Wenrui's Website"
theme = "github.com/lxndrblz/anatole"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en"

[params]
title = "Jiang Wenrui"
author = "Jiang Wenrui"
description = "Agent application and Java backend developer"
profilePicture = "images/live.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
