baseURL = "https://wenrui-jiang.github.io/"
title = "Jiang Wenrui's Website"
theme = "github.com/lxndrblz/anatole"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en"

[params]
title = "I'm Jiang Wenrui"
author = "Jiang Wenrui"
description = "Computer science master's student at Beijing Jiaotong University"
profilePicture = "images/live.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
